# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |v|
    # VM Name
    v.name = "v-Ubuntu-18.04-x64"
    # Customize the amount of memory on the VM:
    v.memory = "2048"
    # CPU Count
    v.cpus = 2
    # Add the box to the Vagrant group
    v.customize ["modifyvm", :id, "--groups", "/VagrantBoxes"]
  end
  # set-up a bridged network adapter
  config.vm.network "public_network", bridge: [
    "ThinkPad Thunderbolt 3 Dock USB Ethernet",
    "Intel(R) Ethernet Connection (4) I219-V"
  ]

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Install stuff
  config.vm.provision "shell", path:"./scripts/init.sh", privileged: false
end
